package example.reviewcollection;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Employee implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private java.lang.String department;

   public Employee()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getDepartment()
   {
      return this.department;
   }

   public void setDepartment(java.lang.String department)
   {
      this.department = department;
   }

   public Employee(java.lang.String name, java.lang.String department)
   {
      this.name = name;
      this.department = department;
   }

}