package org.muni.fi.datamodel;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BicycleOrderAvailableDTO implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String bikeName;

   public BicycleOrderAvailableDTO()
   {
   }

   public java.lang.String getBikeName()
   {
      return this.bikeName;
   }

   public void setBikeName(java.lang.String bikeName)
   {
      this.bikeName = bikeName;
   }

   public BicycleOrderAvailableDTO(java.lang.String bikeName)
   {
      this.bikeName = bikeName;
   }

}