package org.muni.fi.datamodel;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BicycleOrderFormDTO implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String bikeName;
   private java.lang.Short count;

   public BicycleOrderFormDTO()
   {
   }

   public java.lang.String getBikeName()
   {
      return this.bikeName;
   }

   public void setBikeName(java.lang.String bikeName)
   {
      this.bikeName = bikeName;
   }

   public java.lang.Short getCount()
   {
      return this.count;
   }

   public void setCount(java.lang.Short count)
   {
      this.count = count;
   }

   public BicycleOrderFormDTO(java.lang.String bikeName, java.lang.Short count)
   {
      this.bikeName = bikeName;
      this.count = count;
   }

}