package org.muni.fi.datamodel;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class BicycleOrderFormDTO implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public BicycleOrderFormDTO() {
    }

}