package org.muni.fi.datamodel;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CoffeeOrder implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Double volume;
   private java.lang.String location;

   public CoffeeOrder()
   {
   }

   public java.lang.Double getVolume()
   {
      return this.volume;
   }

   public void setVolume(java.lang.Double volume)
   {
      this.volume = volume;
   }

   public java.lang.String getLocation()
   {
      return this.location;
   }

   public void setLocation(java.lang.String location)
   {
      this.location = location;
   }

   public CoffeeOrder(java.lang.Double volume, java.lang.String location)
   {
      this.volume = volume;
      this.location = location;
   }

}