package org.muni.fi.misubprocess_ui;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Item implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private java.lang.Double price;

   public Item()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.Double getPrice()
   {
      return this.price;
   }

   public void setPrice(java.lang.Double price)
   {
      this.price = price;
   }

   public Item(java.lang.String name, java.lang.Double price)
   {
      this.name = name;
      this.price = price;
   }

}