package org.muni.fi.misubprocess_ui;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Order implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.util.List<org.muni.fi.misubprocess_ui.Item> items;

   public Order()
   {
   }

   public java.util.List<org.muni.fi.misubprocess_ui.Item> getItems()
   {
      return this.items;
   }

   public void setItems(java.util.List<org.muni.fi.misubprocess_ui.Item> items)
   {
      this.items = items;
   }

   public Order(java.util.List<org.muni.fi.misubprocess_ui.Item> items)
   {
      this.items = items;
   }

}