package example;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MockupStockDB implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    public static java.util.Map<String,Integer> stockDB = new java.util.HashMap<String,Integer>();
    
    public static Boolean getStockStatus(String key,Integer requestedAmount) {
        
    Integer amount = stockDB.get(key);
        if (amount != null) {
            
            if (amount > 0 ) {
                if (amount > requestedAmount)
                
                return true;
            }
        }
        
        return false; 
    }
    
    public static Integer decreaseStockStatus (String key,Integer amount) {
        
        System.out.println("Decreasing stock status of product:"+key+", by amount -"+amount);
        
        Integer orig = stockDB.get(key);
        Integer newValue = orig - amount;
        stockDB.put(key,newValue);
        return newValue;
    }
    
    static {
        
        System.out.println("initializing stock database");
        
        stockDB.put("nokia",5);
        stockDB.put("macbook",0);
        stockDB.put("headphones",150);
        stockDB.put("fridge",43);
        
        System.out.println("Here is a list of product:");
        
        for (String key: stockDB.keySet()) {
            
            System.out.println(key);
        }
    }

    public MockupStockDB() {
    }

}