package org.muni.fi.businessrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Student implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Integer hw1;
   private java.lang.Integer hw2;
   private java.lang.Integer project;
   private java.lang.Integer bonus;
   private java.lang.Integer uco;
   private java.lang.String grade;
   private java.lang.Integer totalScore;

   public Student()
   {
   }

   public Integer addTotalScore()
   {

      System.out.println("Calculating total score for student " + this.uco);
      Integer tmp = hw1 + hw2 + project + bonus;
      this.totalScore = tmp;
      System.out.println("Total score is " + this.totalScore);
      return this.totalScore;
   }

   public java.lang.Integer getHw1()
   {
      return this.hw1;
   }

   public void setHw1(java.lang.Integer hw1)
   {
      this.hw1 = hw1;
   }

   public java.lang.Integer getHw2()
   {
      return this.hw2;
   }

   public void setHw2(java.lang.Integer hw2)
   {
      this.hw2 = hw2;
   }

   public java.lang.Integer getProject()
   {
      return this.project;
   }

   public void setProject(java.lang.Integer project)
   {
      this.project = project;
   }

   public java.lang.Integer getBonus()
   {
      return this.bonus;
   }

   public void setBonus(java.lang.Integer bonus)
   {
      this.bonus = bonus;
   }

   public java.lang.Integer getUco()
   {
      return this.uco;
   }

   public void setUco(java.lang.Integer uco)
   {
      this.uco = uco;
   }

   public java.lang.String getGrade()
   {
      return this.grade;
   }

   public void setGrade(java.lang.String grade)
   {
      this.grade = grade;
   }

   public java.lang.Integer getTotalScore()
   {
      return this.totalScore;
   }

   public void setTotalScore(java.lang.Integer totalScore)
   {
      this.totalScore = totalScore;
   }

   public Student(java.lang.Integer hw1, java.lang.Integer hw2,
         java.lang.Integer project, java.lang.Integer bonus,
         java.lang.Integer uco, java.lang.String grade,
         java.lang.Integer totalScore)
   {
      this.hw1 = hw1;
      this.hw2 = hw2;
      this.project = project;
      this.bonus = bonus;
      this.uco = uco;
      this.grade = grade;
      this.totalScore = totalScore;
   }

}